### ISSUE TITLE
ASIO support on Windows

### ISSUE THREAD

**Issue by chuckbergeron** [keijiro/Lasp#3]
Hello,

I'm receiving the "LASP: Failed to open the default audio input device." error when I attempt to use my Focusrite Scarlett 18i20 as the default recording device on Windows 10, 64-bit. I've also installed the latest ASIO4All (not sure if that helps or not).

I was however able to use my headphone's mic as the default recording device, and receive info using `AudioInput.CalculateRMSDecibel()`.

Is there some way I could diagnose why my audio interface isn't working with Lasp?

Thanks!

**Comment by keijiro** [comment]
At the moment LASP only supports WASAPI (which is the standard audio API from Windows Vista) because audio latency with it is enough low. That's comparable to ASIO (nearly equal or less than 10 ms).

It seems that the Focusrite audio driver only supports ASIO, so that it doesn't work well with applications that requires other audio APIs.

I think it's better to add ASIO support to LASP but it's a bit troublesome (I still haven't had access to the ASIO SDK), so I have no firm plan about it. My advice at the current point is "please buy a cheap interface and use it instead".

**Comment by chuckbergeron** [comment]
Ah, that makes perfect sense. I didn't realize there was a difference between ASIO and WASAPI. Thanks for the clarification!

**Comment by keijiro** [comment]
After consideration, I concluded that ASIO support is out of the scope of this plugin. I prefer keeping it simple and only dependent on PortAudio.

Now I'm closing this issue. Please feel free to reopen for further questions.
