### ISSUE TITLE
Support on more platforms

### ISSUE THREAD

**Issue by hybridherbst** [keijiro/Lasp#37]
I think due to soundio only supporting Mac & Windows64, LASP is currently only usable on those platforms.
I was wondering if you've got any plans to extend support, maybe not through soundio but through something similar like on your loopback branch (e.g. "regular" audio input?)

(I started a branch with a "SoundIO Shim", but haven't done more than just adding the shim classes so far: https://github.com/prefrontalcortex/Lasp/tree/add-soundio-shim)

**Comment by keijiro** [comment]
It's not difficult to add iOS support (thanks to Core Audio), but I think just adding iOS support doesn't make much sense. What most people need is Android support.

As you may know, handling low-latency audio on Android is quite difficult. I can't afford time and money (to buy lots of test devices) for it.

If there is a multi-platform open source sound library better than soundio, I'll consider replacing it. At the moment, I can't find any good one.

[JUCE](https://juce.com/) was a good candidate, but I rejected it due to the license restriction.

**Comment by hybridherbst** [comment]
Thank you. In the meantime, would be great if you merge https://github.com/keijiro/Lasp/pull/36 which just sets the lasp asmdef correctly so there are no build errors on unsupported platforms. Thanks!
