### ISSUE TITLE
Visual Scripting support

### ISSUE THREAD

**Issue by olgv** [keijiro/Lasp#43]
Now that VS comes as standard with Unity 2021, I can't stop dreaming of LASP integration in VS  : D

**Comment by keijiro** [comment]
I'm sure that you can use LASP with Visual Scripting without any extension/customization.

For Minis and OSCJack, I created extensions because they're hard to use without customization. I think LASP is different from them.

I'm closing this issue now. Please feel free to reopen it if you feel that it's hard to use with Visual Scripting. I'll reconsider it then.
